//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalClinicManagementSystemApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_Table
    {
        public int adminID { get; set; }
        public string username { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string adminTel { get; set; }
    }
}
