//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalClinicManagementSystemApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class appointment_Table
    {
        public string appointmentID { get; set; }
        public string dentalProcedure { get; set; }
        public string patientName { get; set; }
        public System.DateTime appointmentDate { get; set; }
        public string appointmentTime { get; set; }
        public System.DateTime bookingMadeOn { get; set; }
        public string appointmentStatus { get; set; }
        public string dentistID { get; set; }
        public string patientTel { get; set; }
    }
}
