//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalClinicManagementSystemApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class appointment_Table
    {
        public int appointmentID { get; set; }
        public string dentalProcedure { get; set; }
        public int dentistID { get; set; }
        public string patientID { get; set; }
        public System.DateTime appointmentDate { get; set; }
        public string appointmentTime { get; set; }
        public System.DateTime bookingDate { get; set; }
        public string appointmentStatus { get; set; }
        public string dentistStatus { get; set; }
        public string patientTel { get; set; }
    
        public virtual appointment_Table appointment_Table1 { get; set; }
        public virtual appointment_Table appointment_Table2 { get; set; }
    }
}
