//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalClinicManagementSystemApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DentalClinicDbEntities : DbContext
    {
        public DentalClinicDbEntities()
            : base("name=DentalClinicDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin_Table> admin_Table { get; set; }
        public virtual DbSet<appointment_Table> appointment_Table { get; set; }
        public virtual DbSet<dentalProcedure_Table> dentalProcedure_Table { get; set; }
        public virtual DbSet<dentist_Table> dentist_Table { get; set; }
        public virtual DbSet<diagnosis_Table> diagnosis_Table { get; set; }
        public virtual DbSet<patient_Table> patient_Table { get; set; }
        public virtual DbSet<insurance_Table> insurance_Table { get; set; }
    }
}
