//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalClinicManagementSystemApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class dentist_Table
    {
        public int dentistID { get; set; }
        public string dentistName { get; set; }
        public string dentistEmail { get; set; }
        public string dentistTel { get; set; }
        public string password { get; set; }
        public System.DateTime registrationDate { get; set; }
        public string availableDays { get; set; }
    }
}
