//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalClinicManagementSystemApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class diagnosis_Table
    {
        public int diagnosisID { get; set; }
        public string patientID { get; set; }
        public int procedureID { get; set; }
        public string diagnosisDescription { get; set; }
        public System.DateTime diagnosisDate { get; set; }
        public int dentistID { get; set; }
    }
}
