//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalClinicManagementSystemApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient_Table
    {
        public string patientID { get; set; }
        public string patientName { get; set; }
        public string gender { get; set; }
        public string email { get; set; }
        public string patientTel { get; set; }
        public System.DateTime registrationDate { get; set; }
        public int insuranceID { get; set; }
        public string residence { get; set; }
    }
}
